### PR TITLE
Making portfolio

### PR DESCRIPTION
**Pull request by yashasvi25**
Create personal portfolio

### CODE REVIEW

**Comment by rahugur** [comment]
Can you share screenshot of portfolio with these changes.

**Comment by yashasvi25** [comment]
portfolioss
Here is the screenshot. In the portfolio when Get Messages! button is clicked then multiple messages get displayed.

**Comment by rahugur** [comment]
Why button click to fetch comments? You can render them using onLoad.
Keep it as is if you want to make call only on click?

**Comment by yashasvi25** [comment]
In the tutorial it was given the options of using button or using onLoad.This is just for the tutorial. I can make changes to render using onLoad. I will attach the screenshot after making changes.

**Comment by yashasvi25** [comment]
ss_portfolio
Screenshot after using onLoad attribute

**Comment by rahugur** [comment]
Ah, didn't know tutorial gave this option.
LGTM! Avoid pushing commented/redundant code.

**Comment by yashasvi25** [comment]
ss_get_port_beforeadding
Screenshot of portfolio before adding a comment
ss_addingcomment
Screenshot of portfolio after adding a comment

**Pull request merged**
